config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
   
    path('', include('core.login.urls')),
    path('admin/', admin.site.urls),
    path('erp/',include('core.erp.urls')),
    path('user/',include('core.user.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path
from core.erp.view404 import PageNotFoundView
from core.erp.views.evidenciaU.views import *
from core.erp.views.empresas.views import *
from core.erp.views.evidenciaA.views import *
from core.erp.views.evidenciaMI.views import *
from core.erp.views.evidenciaMEF.views import *
from core.erp.views.evidenciaMPI.views import *
from core.erp.views.evidenciaMRC.views import *
handler404 = PageNotFoundView.as_view()
app_name = 'erp'
urlpatterns = [
    #EMPRESAS
    path('empresa/list/',ListViewEmpresa.as_view(),name='empresa_list'),
    path('empresa/add/',CreateViewEmpresa.as_view(),name='empresa_create'),
    path('empresa/edit/<int:pk>/',UpdateViewEmpresa.as_view(),name='empresa_edit'),
    path('empresa/delete/<int:pk>/',DeleteViewEmpresa.as_view(),name='empresa_delete'),

    #EVIDENCIAS UNICAS
    path('evidenciaU/list/',ListViewEvidenciaU.as_view(),name='eu_list'),
    path('evidenciaU/add/',CreateViewEvidenciaU.as_view(),name='eu_create'),
    path('evidenciaU/edit/<int:pk>/',UpdateViewEvidenciaU.as_view(),name='eu_edit'),
    path('evidenciaU/delete/<int:pk>/',DeleteViewEvidenciaU.as_view(),name='eu_delete'),
    #EVIDENCIAS MENSUALES IMPUESTOS
    path('evidenciaMI/list/',ListViewEvidenciaMI.as_view(),name='emi_list'),
    path('evidenciaMI/add/',CreateViewEvidenciaMI.as_view(),name='emi_create'),
    path('evidenciaMI/edit/<int:pk>/',UpdateViewEvidenciaMI.as_view(),name='emi_edit'),
    path('evidenciaMI/delete/<int:pk>/',DeleteViewEvidenciaMI.as_view(),name='emi_delete'),
    #EVIDENCIAS MENSUALES PRESENTACION DE IMPUESTOS
    path('evidenciaMPI/list/',ListViewEvidenciaMPI.as_view(),name='empi_list'),
    path('evidenciaMPI/add/',CreateViewEvidenciaMPI.as_view(),name='empi_create'),
    path('evidenciaMPI/edit/<int:pk>/',UpdateViewEvidenciaMPI.as_view(),name='empi_edit'),
    path('evidenciaMPI/delete/<int:pk>/',DeleteViewEvidenciaMPI.as_view(),name='empi_delete'),
    #EVIDENCIAS MENSUALES REGISTROS CONTABLES
    path('evidenciaMRC/list/',ListViewEvidenciaMRC.as_view(),name='emrc_list'),
    path('evidenciaMRC/add/',CreateViewEvidenciaMRC.as_view(),name='emrc_create'),
    path('evidenciaMRC/edit/<int:pk>/',UpdateViewEvidenciaMRC.as_view(),name='emrc_edit'),
    path('evidenciaMRC/delete/<int:pk>/',DeleteViewEvidenciaMRC.as_view(),name='emrc_delete'),
    #EVIDENCIAS MENSUALES ESTADOS FINANCIEROS
    path('evidenciaMEF/list/',ListViewEvidenciaMEF.as_view(),name='emef_list'),
    path('evidenciaMEF/add/',CreateViewEvidenciaMEF.as_view(),name='emef_create'),
    path('evidenciaMEF/edit/<int:pk>/',UpdateViewEvidenciaMEF.as_view(),name='emef_edit'),
    path('evidenciaMEF/delete/<int:pk>/',DeleteViewEvidenciaMEF.as_view(),name='emef_delete'),
    #EVIDENCIAS ANUALES
    path('evidenciaA/list/',ListViewEvidenciaA.as_view(),name='ea_list'),
    path('evidenciaA/add/',CreateViewEvidenciaA.as_view(),name='ea_create'),
    path('evidenciaA/edit/<int:pk>/',UpdateViewEvidenciaA.as_view(),name='ea_edit'),
    path('evidenciaA/delete/<int:pk>/',DeleteViewEvidenciaA.as_view(),name='ea_delete'),
]

core/user/urls.py
from django.urls import path
from core.user.views import *
app_name = 'user'

urlpatterns = [
    # user
    path('list/', ListViewUser.as_view(), name='user_list'),
    path('add/', CreateViewUser.as_view(), name='user_create'),
    path('update/<int:pk>/', UpdateViewUser.as_view(), name='user_update'),
    path('delete/<int:pk>/', DeleteViewUser.as_view(), name='user_delete'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
]

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>{{request.user.get_full_name}}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entidad }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script type="">
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="" class="nav-link">Home</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if request.user.groups.all %}
            <li class="nav-item dropdown">
                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}</a>
                {% if request.user.groups.all.count > 1 %}
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                        style="left: 0px; right: inherit;">
                        {% for g in request.user.groups.all %}
                            {% if g.id != request.session.group.id %}
                                <li><a href="{% url 'user:user_change_group' g.id %}"
                                       class="dropdown-item">{{ g.name }} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="">
                <i class="fas fa-users-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Sú último acceso fue {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="">
        <img src="{% static 'img/logo.png' %}" alt="full computer" class="brand-image elevation-3 bg-primary"
            style="opacity: .8;width:100%">
        <span class="brand-text font-weight-light">SISTEMA DE CONTRATOS</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.get_image }}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{request.user.username}}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Mantenimientos</li>
               
                {% if request.user.is_superuser %}
                    <li class="nav-item">
                        <a href="{% url 'user:user_list'%}" class="nav-link">
                            <i class="nav-icon fas fa-user"></i>
                            <p>
                                Usuarios
                            </p>
                        </a>
                    </li>
                {% endif %}
               

                <li class="nav-item">
                    <a href="{% url 'erp:empresa_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-building"></i>
                        <p>
                            Clientes
                        </p>
                    </a>
                </li>

                <li class="nav-item" >
                    <a href="#" class="nav-link" >
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Control ISO 9001
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" >
                        <li class="nav-item">
                            <a href="{% url 'erp:eu_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Evidencia Unica</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:emi_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Evidencia MI</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:emef_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Evidencia MEF
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:empi_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Evidencia MPI</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:emrc_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Evidencia MRC</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:ea_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Evidencia Anual</p>
                            </a>
                        </li>
                        
                    </ul>
                </li>
               
            </ul>
        </nav>
    </div>
</aside>